### PR TITLE
Upgrade to PyQt6

### LINKED ISSUE #80: upgrade to use pyqt6 instead of pyqt5
Could this package be upgraded to use the latest version of pyqt? this is to make it work better with m1 based Mac

### PR DESCRIPTION
**Pull request by chadykamar**
resolves #80

### CODE REVIEW

**Comment by hennr** [comment]
I can confirm that this works under Linux (debian testing in my case)

```
pip3 install PyQt6-WebEngine
pip3 install PyQt6
pip3 install git+https://github.com/chadykamar/openconnect-sso.git@master
```

Thanks @chadykamar 

Any chance to get this merged and a new release out @vlaci ?

**Comment by greenaussie** [comment]
Can I vote for this merge :) Thanks for all the work.

**Comment by vlaci** [comment]
Thank you!

**Comment by MrAnno** [comment]
@vlaci This is becoming more and more necessary on Arch Linux.

Do you have plans to release a new openconnect-sso version in the near future?

I'm asking because if not, I'm going to add a workaround in AUR on top of v0.8.0.

**Pull request merged**
