### PR TITLE
fix: nix & python packages upgrade, csd verify file

### PR DESCRIPTION
**Pull request by adminy**
adds  `-k` / `--skip-ssl-verification` and `-f`  / `--scan-file` flags.
Tested with and without ssl verification.

Usage in case using newer openssl:
```bash
export OCF="openssl_conf = openssl_init\n[openssl_init]\nssl_conf = ssl_sect\n[ssl_sect]\nsystem_default = system_default_sect\n[system_default_sect]\nOptions = UnsafeLegacyRenegotiation"

echo -e $OCF | OPENSSL_CONF=/dev/stdin openconnect-sso -s vpn.comapny-name.com -f host-scan
```

Example `host-scan` file:
```
endpoint.device.protection_version="4.10.04071";
```
Fjxes:
- #152
- #102
- #99 
- #35

### Usage in nix:

`flake.nix`:
```nix
inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/master";
    systems.url = "github:nix-systems/x86_64-linux";
    flake-utils = { url = "github:numtide/flake-utils"; inputs.systems.follows = "systems"; };
    openconnect-sso = {
      url = github:adminy/openconnect-sso/newer-versions;
      inputs.flake-utils.follows = "flake-utils";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.systems.follows = "systems";
    };
};
```
`configuration.nix`:
```nix
environment.systemPackages = [
  inputs.openconnect-sso.packages.${config.nixpkgs.localSystem.system}.default
];
```

### CODE REVIEW

**Comment by Cadair** [comment]
Hi @adminy thanks for this work, it fixed my build. I wondered if you had any clue as to why I am getting the following error:

```
[error    ] Required attributes not found in response ("no such child: host-scan", does this endpoint do SSO?), exiting [openconnect_sso.app]
```

Any pointers would be super helpful thanks!

**Comment by adminy** [comment]
My PR makes an assumtion that there is always a host-scan file passed for CPD verification. I can update that to make this optional, sounds like a bug.

**Comment by adminy** [comment]
hopefully I haven't left anything out. Should be fixed now.

**Comment by Cadair** [comment]
Hi @adminy I have just tried your latest commit and I am getting the same error.

**Comment by ThinkChaos** [comment]
Hey, it's been a while since I posted in my PR (#152) reposting here for visibility:
> please rebase your PR on mine [to include my commit in the history], because using my work without attribution is not cool

**Comment by adminy** [comment]
hey @ThinkChaos, I kind of no longer use this VPN client, but I rebased your changes like you asked. Seems like a dead project anyways since our PRs aren't being merged in.

**Comment by ThinkChaos** [comment]
Thanks appreciate it!

Out of curiosity what are you using instead?

**Comment by adminy** [comment]
I was using this client for work, but my workplace did not appreciate me working on linux. So Now I'm somewhere else and occasionally I use openvpn cli client to connect to AWS's vpn client serverless solution. Personally though, to go through my devices I use [rathole](https://github.com/rapiz1/rathole). Its the simplest in design and much much faster.

**Comment by ThinkChaos** [comment]
> So Now I'm somewhere else

:clap: 

Thanks for the info :)

**Comment by AV00** [comment]
@adminy Is your fork available in any way ? I have the same issues that this pull request was intended to fix, but I see no way to get those patches.
Thanks.

**Comment by adminy** [comment]
just apply it as a patch file: https://github.com/vlaci/openconnect-sso/pull/181.patch

**Pull request closed without merging**
