### PR TITLE
Updating keyring to 22.0.1

### PR DESCRIPTION
**Pull request by MrAnno**

### CODE REVIEW

**Comment by MrAnno** [comment]
@vlaci Arch Linux updated their [keyring](https://archlinux.org/packages/community/any/python-keyring/) version to 22.0.

I'm not sure how keyring versioning works (does not look like semantic versioning), but 22.0 seems to be backwards compatible.

**Comment by MrAnno** [comment]
@vlaci Are you planning to release a new version in the near future? :)

I'm asking this because the Arch Linux AUR package is currently broken due to `keyring` being updated.
I can also apply this patch on top of v0.6.1 in case v0.6.2 is not on your radar.

**Comment by vlaci** [comment]
Sure, I'll draft a new release.

**Comment by MrAnno** [comment]
Thank you very much.

**Comment by vlaci** [comment]
Done

**Pull request merged**
