### PR TITLE
Fixed MFA

### LINKED ISSUE #53: Support WebAuthn
First of all thank you so much for building this nice wrapper. This made it so much easier for me to connect to my VPN from Linux system.

However, I recently switched from traditional OTP based MFA to a security key (YubiKey) based MFA. But I can't seem to get it to work with `openconnect-sso` because it does not open a new popup dialog box which should ask me to connect my YubiKey and tap it.

Logs:
```
$ openconnect-sso --server vpn.server.company.com/ssl --authenticate shell --browser-display-mode shown
[info     ] Authenticating to VPN endpoint [openconnect_sso.app] address=vpn.server.company.com/ssl name=
[info     ] Response received              [openconnect_sso.authenticator] id=main message=Please complete the authentication process in the AnyConnect Login window. title=Login
[info     ] Browser started                [webengine] startup_info=StartupInfo(url='https://vpn.server.company.com/+CSCOE+/saml/sp/login?tgname=SSL_Profile&acsamlcap=v2', credentials=None)
[info     ] Loading page                   [webengine] url=https://vpn.server.company.com/+CSCOE+/saml/sp/login?tgname=SSL_Profile&acsamlcap=v2
js: WARNING: `getUserProfile` does not support requests for  dsc .
js: Refused to load the image 'https://duo.com/' because it violates the following Content Security Policy directive: "img-src 'self'  ".

js: Refused to load the image 'https://duo.com/' because it violates the following Content Security Policy directive: "img-src 'self'  ".

js: Refused to load the image 'https://duo.com/' because it violates the following Content Security Policy directive: "img-src 'self'  ".

^C 
$
```
Ignore the `js: ` errors, they have always been there even when this was working fine with OTP based MFA.

---
The browser screen asks for login credentials, then upon successful login, shows the following screen:

Screenshot from 2021-04-05 15-41-39

After clicking the `Use Security Key` button, I expect to see a new dialog box but nothing happens. The screen changes to following but nothing appears:

Screenshot from 2021-04-05 15-41-59

Would be great if you can point me in the right direction for troubleshooting. Is this expected behavior? Is this a problem specific to [WebAuthn](https://webauthn.io/) or is it not possible to show any new popup dialog boxes in the current `openconnect-sso` login flow?

### PR DESCRIPTION
**Pull request by marekdedic**
Should close #53

### CODE REVIEW

**Comment by vlaci** [comment]
I cannot try this out anymore, I hope that it works :)

**Comment by marekdedic** [comment]
I've been using it daily and it has worked for me so far 🙂

Thanks

**Comment by marekdedic** [comment]
Hi,
sorry to bother you, but could you please release this? I'd like to get back to not depending on my own fork :) Thanks!

**Comment by ojg** [comment]
I also came here looking for a solution to using openconnect-sso with Yubikey. So I am anxiously waiting for a new release with this functionality.

Thank you for a great piece of software that has made work from home so much easier for me.

**Comment by vlaci** [comment]
I have released 0.8.0 but doesn't want to upload to pypi without testing. If you could try it manually from [here](https://github.com/vlaci/openconnect-sso/releases/tag/v0.8.0) and report back if it works for you that would be much appreciated.

**Comment by ojg** [comment]
Thank you very much for providing this for me to test.

I'm not an expert pip user so I might have done something wrong during the install. If I just do
"pipx install openconnect-sso-0.8.0/" then I will get "ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'" even though "pipx list" shows pyqt5 installed.

So I had to do "pipx install openconnect-sso[full]" and then "pipx install --force openconnect-sso-0.8.0/" before it would run at all without pyqt5 error.
"openconnect-sso --version" now reports 0.8.0

However, it didn't work for me, just like with 0.7.3, no popup window appeared after selecting "secret key" and pressing said key.

**Comment by paalge** [comment]
I don't get a window in 0.8.0 either. No error message with log level debug.

**Comment by marekdedic** [comment]
Hi,
I just did
```
$ git checkout v0.8.0
$ make clean
$ make dist
$ pip install dist/openconnect-sso-0.8.0.tar.gz
```

And I have version 0.8.0 installed successfully, and I do get the popup window.

**Comment by marekdedic** [comment]
Hi, @vlaci, do you please have any plans on releasing this to pip? Works for me like a charm ever since the merge...

Thanks!

**Pull request merged**
